### ISSUE TITLE
How to install?

### ISSUE THREAD

**Issue by zwolfinger** [rfratto/vscode-river#1]
I'm interested in adding river support to my VSCode.  How does this get installed?

**Comment by rfratto** [comment]
Until the plugin is published on the VSCode marketplace, the way to install this is to go to one of the [releases](https://github.com/rfratto/vscode-river/releases/tag/v0.1.0-alpha.2) and [download and install the VSIX file](https://code.visualstudio.com/docs/editor/extension-marketplace#_install-from-a-vsix).

**Comment by rfratto** [comment]
Closing as answered. Thanks for the interest!
