### ISSUE TITLE
.vsix-File is missing

### ISSUE THREAD

**Issue by trc-ikeskin** [rfratto/vscode-river#5]
In your README you state the following:

> You can install it in VS Code using the .vsix in this repository.

Unfortunately the file is missing from your repository. Please consider publishing pre-built versions of this extension.

**Comment by rfratto** [comment]
Hi, they are available here: https://github.com/rfratto/vscode-river/releases

It's considered pre-release so it doesn't show up on the home page of the repo, unfortunately.

**Comment by trc-ikeskin** [comment]
Thank you for pointing me there! :+1:
